# Generated by Django 4.0.4 on 2022-06-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de contacto')),
                ('NombreP', models.CharField(max_length=10, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=10, verbose_name='Apellido')),
                ('Email', models.CharField(max_length=20, verbose_name='E-mail')),
                ('Asunto', models.CharField(max_length=9, verbose_name='Asunto')),
                ('Asunto2', models.CharField(max_length=20, verbose_name='Asunto2')),
            ],
        ),
        migrations.CreateModel(
            name='Registroo',
            fields=[
                ('idRegistro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de registro')),
                ('Nombre', models.CharField(max_length=6, verbose_name='Nombre')),
                ('Edad', models.CharField(max_length=2, verbose_name='Edad')),
                ('Email', models.CharField(max_length=20, verbose_name='E-mail')),
                ('Telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('Contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
    ]
