# Generated by Django 4.0.4 on 2022-06-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Registroo',
        ),
    ]
