# Generated by Django 4.0.4 on 2022-06-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Registroo',
        ),
    ]
