# Generated by Django 4.0.5 on 2022-06-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('nombre', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Registroo',
        ),
    ]
