# Generated by Django 4.0.5 on 2022-06-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clientes_productos_delete_contacto_delete_registroo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='productos',
            new_name='Producto',
        ),
    ]
